name: autopep8 
on: pull_request
jobs: 
  autopep8:
  # Check if PR is created by this workflow and not by a fork 
    if: startsWith(github.head_ref, 'autopep8-patches') == false && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1 
        with: 
          args: --exit-code --recursive --in-place --aggressive --aggressive . 
      - name: Commit autopep8 changes 
        if: steps.autopep8.output.exit-code == 2
        run: | 
          git config --global user.name 'Akshay Finney'
          git config --global user.email 'akshaygf@gmail.com'
          git commit -am "Automated autopep8 fixes"
          git push